// Shared D.O.G. Help Content — used by both DeckOutlineGenerator help modal and HelpPage
// IMPORTANT: This is the single source of truth for D.O.G. help text.

export const DOG_HELP_SIDEBAR_ITEMS = [
  { id: 'overview', label: 'Overview' },
  { id: 'workflow', label: 'Basic Workflow' },
  { id: 'tips', label: 'Tips & Best Practices' },
  { id: 'upload', label: 'Document Upload' },
  { id: 'prompting', label: 'Deck Context & Prompting' },
  { id: 'editing', label: 'Editing & Regenerating' },
  { id: 'system-prompts', label: 'System Prompts' },
  { id: 'output-format', label: 'Output Format' },
  { id: 'theme', label: 'Theme Generator' },
  { id: 'image-prompts', label: 'Image Prompt Generation' },
  { id: 'asset-placement', label: 'Visual Asset Placement' },
  { id: 'layouts', label: 'Slide Layouts' },
  { id: 'settings', label: 'Settings Panel' },
  { id: 'slides-extension', label: 'Download Slides Extension' },
];

// Light-theme CSS overrides — applied when theme="light" via a wrapper class
const LIGHT_THEME_STYLES = `
.help-light .text-orange-400 { color: #1c1917 !important; }
.help-light .text-orange-400\\/70 { color: #44403c !important; }
.help-light h3.text-sm { color: #1c1917 !important; }
.help-light h4.text-xs { color: #1c1917 !important; }
.help-light .text-stone-300 { color: #1c1917 !important; }
.help-light .text-stone-400 { color: #44403c !important; }
.help-light .text-stone-500 { color: #57534e !important; }
.help-light .text-xs.text-stone-300 { color: #292524 !important; }
.help-light .bg-stone-900 { background-color: rgba(255,255,255,0.35) !important; }
.help-light .bg-stone-950 { background-color: rgba(255,255,255,0.25) !important; }
.help-light .border-stone-700 { border-color: rgba(0,0,0,0.1) !important; }
.help-light .bg-orange-500\\/10 { background-color: #57534e !important; }
.help-light .border-orange-500\\/30 { border-color: #44403c !important; }
.help-light .bg-orange-500\\/10 h3 { color: #fb923c !important; }
.help-light .bg-orange-500\\/10 ul { color: #fdba74 !important; }
.help-light .bg-orange-500\\/10 li { color: #fdba74 !important; }
.help-light a[download] { border-left-color: #1c1917 !important; background-color: rgba(255,255,255,0.25) !important; }
.help-light a[download]:hover { background-color: rgba(255,255,255,0.4) !important; }
.help-light a[download] .text-orange-400 { color: #1c1917 !important; }
.help-light a[download] .text-stone-500 { color: #57534e !important; }
`;

export function DogHelpContent({ helpPage, theme }) {
  const isLight = theme === 'light';
  return (
    <>
      {isLight && <style>{LIGHT_THEME_STYLES}</style>}
      <div className={isLight ? 'help-light' : ''}>
      {/* ═══ OVERVIEW ═══ */}
      {helpPage === 'overview' && (
      <div className="space-y-5">
      <section>
        <h3 className="text-sm font-bold text-orange-400 uppercase tracking-wide mb-3">Overview</h3>
        <p className="text-xs text-stone-300 leading-relaxed mb-4">
          D.O.G. (Deck Outline Generator) is an AI-powered tool that transforms your project documentation into structured presentation slide outlines.
          Upload your source materials (PDFs, markdown files, text files, or images), provide context about your deck, and generate either individual slides or complete deck outlines.
        </p>
        <div className="space-y-3">
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Key Features</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Single page or full deck generation</span> — Generate individual slides or entire presentations at once</li>
              <li>• <span className="text-stone-300">15 slide layout types</span> — Title slides, two/three/four columns, big numbers, captions, and more</li>
              <li>• <span className="text-stone-300">Dynamic visual asset sizing</span> — Image heights auto-adjust based on text content volume in column layouts</li>
              <li>• <span className="text-stone-300">AI theme color generation</span> — Context-aware color palettes generated by Haiku AI</li>
              <li>• <span className="text-stone-300">Live slide visualizer</span> — Preview layouts with theme colors and asset placeholders</li>
              <li>• <span className="text-stone-300">AI rewrite tools</span> — Rewrite selected text with tone adjustments (Relaxed, Formal, Extend, Shorten, Custom)</li>
              <li>• <span className="text-stone-300">Formatting toolbar</span> — Bold, italic, bullets, numbered lists, and heading formatting</li>
              <li>• <span className="text-stone-300">Visual asset placement</span> — Upload your own images/videos and let the AI place them into contextually matching slide frames</li>
              <li>• <span className="text-stone-300">Image prompt generation</span> — Generate AI image prompts for all visual assets at export time</li>
              <li>• <span className="text-stone-300">Customizable system prompts</span> — Full control over AI instructions and output formats</li>
              <li>• <span className="text-stone-300">Custom export folder</span> — Choose a specific folder for exported files with remembered location</li>
              <li>• <span className="text-stone-300">Export as markdown</span> — Download as DECKOUTLINE.md or VIS_DECKOUTLINE.md with theme data</li>
            </ul>
          </div>
        </div>
      </section>
      </div>
      )}

      {/* ═══ BASIC WORKFLOW ═══ */}
      {helpPage === 'workflow' && (
      <div className="space-y-5">
      <section>
        <h3 className="text-sm font-bold text-orange-400 uppercase tracking-wide mb-3">Basic Workflow</h3>
        <div className="text-xs text-stone-300 leading-relaxed space-y-2">
          <p><span className="text-orange-400 font-bold">1. Upload Documents:</span> Add up to 5 source files (PDFs, markdown, text, or images) that contain your project information.</p>
          <p><span className="text-orange-400 font-bold">2. Set Deck Context:</span> Provide guidelines about the overall tone, style, and objectives for your presentation.</p>
          <p><span className="text-orange-400 font-bold">3. Choose Mode:</span> Toggle "Full Deck" to generate an entire presentation, or leave it off to generate individual slides.</p>
          <p><span className="text-orange-400 font-bold">4. For Single Pages:</span> Select a layout type, optionally set a page number, and describe what content you want on the slide.</p>
          <p><span className="text-orange-400 font-bold">5. Generate & Review:</span> Generated outlines appear in the output panel. Use the visualizer to preview layouts with theme colors, or edit the raw markdown.</p>
          <p><span className="text-orange-400 font-bold">6. Refine Output:</span> Use the Edit Output bar to regenerate pages with revision notes, change layouts, and undo/redo changes.</p>
          <p><span className="text-orange-400 font-bold">7. Theme Colors:</span> Enable "Theme Generator" to auto-generate AI color palettes. Cycle through themes with arrow buttons. Refresh for new options.</p>
          <p><span className="text-orange-400 font-bold">8. Export:</span> Download as DECKOUTLINE.md, or check "Include theme colors" for VIS_DECKOUTLINE.md with theme data and visual descriptions.</p>
          <p><span className="text-orange-400 font-bold">9. Image Prompts (Optional):</span> Enable "Generate Image Prompts" in the export modal to create AI image prompts for all visual assets. Select your target model (Midjourney, Flux, Nano Banana, or ChatGPT) and download alongside your outline.</p>
        </div>
      </section>
      </div>
      )}

      {/* ═══ DOCUMENT UPLOAD ═══ */}
      {helpPage === 'upload' && (
      <div className="space-y-5">
      <section>
        <h3 className="text-sm font-bold text-orange-400 uppercase tracking-wide mb-3">Document Upload Best Practices</h3>
        <p className="text-xs text-stone-300 leading-relaxed mb-3">
          The quality of your uploaded documents directly impacts the quality of generated slides. The system reads and references your documents as context when generating content.
        </p>
        <div className="space-y-3">
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Ideal Document Types</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Project briefs or creative briefs</span> — Best for giving the AI a clear understanding of goals, audience, and scope</li>
              <li>• <span className="text-stone-300">Content outlines or structured notes</span> — Pre-organized content translates directly into well-structured slides</li>
              <li>• <span className="text-stone-300">Marketing copy or messaging documents</span> — Provides exact language, taglines, and key phrases to pull from</li>
              <li>• <span className="text-stone-300">Data sheets or fact sheets</span> — Great for generating Big Number and data-driven slide layouts</li>
              <li>• <span className="text-stone-300">Reference images</span> — Upload mood boards or style references to inform visual styling suggestions</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Tips for Better Document Input</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Use clear headers and sections</span> in your documents — the AI can better extract relevant content when it's well-organized</li>
              <li>• <span className="text-stone-300">Include specific data points</span> (stats, percentages, timelines) if you want them surfaced in slides</li>
              <li>• <span className="text-stone-300">Keep documents focused</span> — a concise 2-page brief outperforms a 50-page document dump</li>
              <li>• <span className="text-stone-300">Multiple smaller files &gt; one massive file</span> — split content by topic area (e.g., one for strategy, one for visuals, one for copy)</li>
              <li>• <span className="text-stone-300">Avoid scanned PDFs</span> — machine-readable text extracts cleanly, while scanned images may not</li>
              <li>• <span className="text-stone-300">Name your files descriptively</span> — "Q3_Marketing_Strategy.pdf" gives the AI better context than "doc1.pdf"</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">What to Avoid</h4>
            <ul className="text-[11px] text-stone-500 leading-relaxed space-y-1 ml-2">
              <li>• Raw meeting transcripts with lots of filler — clean and summarize first</li>
              <li>• Documents with heavy formatting or tables that may not parse well</li>
              <li>• Uploading only images with no text context — pair images with a written brief</li>
              <li>• Contradictory documents — if you upload two files with conflicting info, the AI may produce inconsistent slides</li>
            </ul>
          </div>
        </div>
      </section>
      </div>
      )}

      {/* ═══ DECK CONTEXT & PROMPTING ═══ */}
      {helpPage === 'prompting' && (
      <div className="space-y-5">
      <section>
        <h3 className="text-sm font-bold text-orange-400 uppercase tracking-wide mb-3">Deck Context & Page Request Prompting</h3>
        <p className="text-xs text-stone-300 leading-relaxed mb-3">
          Your Deck Context and Page Request prompts are the primary way you steer the AI. Specific, well-structured prompts produce dramatically better results than vague ones.
        </p>
        <div className="space-y-3">
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Deck Context (Section 1) — Best Practices</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed mb-2">
              This field sets the tone for every slide generated in the session. Think of it as the creative director's brief.
            </p>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Define your audience</span> — "This deck is for C-suite executives at a Fortune 500 retail company"</li>
              <li>• <span className="text-stone-300">Set the visual tone</span> — "Dark, cinematic aesthetic with noir influences" or "Clean, minimal, modern SaaS style"</li>
              <li>• <span className="text-stone-300">Specify the purpose</span> — "Sales pitch to close a $2M deal" vs "Internal team kickoff for Q3 initiative"</li>
              <li>• <span className="text-stone-300">Mention brand guidelines</span> — "Use formal language, avoid slang, always refer to product as 'Platform' not 'app'"</li>
              <li>• <span className="text-stone-300">Include page count for Full Deck</span> — "Create a 12-slide presentation with a clear narrative arc"</li>
            </ul>
            <div className="mt-3">
              <p className="text-[11px] text-orange-400 font-bold mb-1">Example — Strong Deck Context:</p>
              <p className="text-[10px] text-stone-500 bg-stone-950 p-2 rounded font-mono leading-relaxed">
                "Create a 10-slide pitch deck for ZeroSpace's holographic display technology. Target audience: brand marketing directors at luxury fashion houses. Tone: premium, forward-thinking, slightly provocative. Emphasize ROI and experiential impact. Use data from the uploaded case studies. Visual style: dark backgrounds, gold/amber accents, large hero imagery."
              </p>
            </div>
            <div className="mt-2">
              <p className="text-[11px] text-orange-400 font-bold mb-1">Example — Weak Deck Context:</p>
              <p className="text-[10px] text-stone-500 bg-stone-950 p-2 rounded font-mono leading-relaxed">
                "Make a nice presentation about our company."
              </p>
            </div>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Page Request (Section 2) — Best Practices</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed mb-2">
              The page request tells the AI exactly what content you want on a specific slide. The more specific you are, the better the output.
            </p>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Reference your documents</span> — "Use the pricing data from the uploaded brief to create a comparison slide"</li>
              <li>• <span className="text-stone-300">Be specific about content</span> — "Cover the 3 key differentiators: speed, quality, and cost" not just "differentiators slide"</li>
              <li>• <span className="text-stone-300">Mention the slide's role in the deck</span> — "This is the closing slide after the case studies section"</li>
              <li>• <span className="text-stone-300">Specify data to include</span> — "Include the stat about 40% engagement increase from the case study"</li>
              <li>• <span className="text-stone-300">Describe the visual you want</span> — "Hero image of the holographic display on the left, key specs on the right"</li>
            </ul>
            <div className="mt-3">
              <p className="text-[11px] text-orange-400 font-bold mb-1">Example — Strong Page Request:</p>
              <p className="text-[10px] text-stone-500 bg-stone-950 p-2 rounded font-mono leading-relaxed">
                "Create a 'Title and two columns' slide comparing traditional LED activations vs ZeroSpace holographic experiences. Left column: limitations of LED (flat, static, high setup cost). Right column: benefits of holographic (3D, interactive, modular). Pull specific metrics from the uploaded ROI document."
              </p>
            </div>
          </div>
        </div>
      </section>
      </div>
      )}

      {/* ═══ EDITING & REGENERATING ═══ */}
      {helpPage === 'editing' && (
      <div className="space-y-5">
      <section>
        <h3 className="text-sm font-bold text-orange-400 uppercase tracking-wide mb-3">Editing & Regenerating Output</h3>
        <p className="text-xs text-stone-300 leading-relaxed mb-3">
          After generating a slide, the Edit Output bar gives you powerful tools to refine content without starting over.
        </p>
        <div className="space-y-3">
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Edit Output Bar Controls</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li>• <span className="text-stone-300">Revision Prompt</span> — Type specific instructions for how the slide should change (e.g., "make the title punchier" or "add a bullet about timeline")</li>
              <li>• <span className="text-stone-300">Layout Dropdown</span> — Switch to a different layout type during regeneration. Select "Keep layout" to preserve the current one</li>
              <li>• <span className="text-stone-300">Regenerate Page</span> — Sends the current slide content + your revision notes back to the AI for a new version</li>
              <li>• <span className="text-stone-300">Undo (&#8630;)</span> — Reverts to the previous version before the last regeneration</li>
              <li>• <span className="text-stone-300">Redo (&#8631;)</span> — Re-applies a version you just undid</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Regeneration Tips</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Be specific with revisions</span> — "Shorten all bullet points to under 8 words" works better than "make it shorter"</li>
              <li>• <span className="text-stone-300">Use revision + layout change together</span> — Switch to "Big number" and type "Focus on the 40% engagement stat" for a complete pivot</li>
              <li>• <span className="text-stone-300">Iterate incrementally</span> — Make one change at a time so you can undo precisely if needed</li>
              <li>• <span className="text-stone-300">Press Enter</span> in the revision prompt field to trigger regeneration quickly</li>
              <li>• <span className="text-stone-300">Leave revision empty</span> to get a fresh take on the same content without specific direction</li>
              <li>• <span className="text-stone-300">Manual editing</span> — Switch to text view (code icon) to directly edit the markdown if you just need small tweaks</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Text View vs Visualizer</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed">
              Toggle between <span className="text-stone-300">text view</span> (code icon) for raw markdown editing and the <span className="text-stone-300">visualizer</span> (eye icon) for a layout preview with theme colors and asset placeholders.
              Edits in text view are live — the visualizer updates immediately to reflect your changes.
            </p>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">AI Rewrite</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed mb-2">
              Select any text in the output editor and right-click to access AI rewrite options. Available modes:
            </p>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Relaxed:</span> Makes text more casual and conversational</li>
              <li>• <span className="text-stone-300">Formal:</span> Elevates language to a professional, polished tone</li>
              <li>• <span className="text-stone-300">Extend:</span> Expands the selected text with more detail and depth</li>
              <li>• <span className="text-stone-300">Shorten:</span> Condenses text while preserving key meaning</li>
              <li>• <span className="text-stone-300">Custom:</span> Type your own rewrite instruction for full control</li>
            </ul>
            <p className="text-[11px] text-stone-500 mt-2">
              Rewrite prompts can be customized in Settings &rarr; Prompts tab &rarr; "AI Rewrite Prompts" section.
            </p>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Formatting Toolbar</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed mb-2">
              The formatting toolbar appears above the text editor (hidden in visualizer view) and provides quick formatting shortcuts:
            </p>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Bold (B):</span> Wraps selected text in **bold** markers</li>
              <li>• <span className="text-stone-300">Italic (I):</span> Wraps selected text in *italic* markers</li>
              <li>• <span className="text-stone-300">Bullet List:</span> Converts lines to bulleted list items</li>
              <li>• <span className="text-stone-300">Numbered List:</span> Converts lines to numbered list items with auto-increment</li>
              <li>• <span className="text-stone-300">Heading:</span> Adds heading markers to selected text</li>
            </ul>
            <p className="text-[11px] text-stone-500 mt-2">
              Press Enter at the end of a bullet or numbered list item to automatically continue the list on the next line.
            </p>
          </div>
        </div>
      </section>
      </div>
      )}

      {/* ═══ SYSTEM PROMPTS ═══ */}
      {helpPage === 'system-prompts' && (
      <div className="space-y-5">
      <section>
        <h3 className="text-sm font-bold text-orange-400 uppercase tracking-wide mb-3">Understanding System Prompts</h3>
        <p className="text-xs text-stone-300 leading-relaxed mb-3">
          System prompts are the instructions that tell the AI how to generate your slide content. They control everything from formatting rules to content style.
          There are two types of prompts for each generation mode (single page and full deck), and understanding their purpose is key to customizing the tool effectively.
        </p>
        <div className="space-y-3">
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">API System Message</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed mb-2">
              This is the core instruction sent to the AI model as its "system" directive. It establishes the AI's fundamental role and behavior before it sees any of your content.
              Think of it as the AI's "job description" - it tells the AI what kind of assistant it should be.
            </p>
            <div className="mt-3 space-y-2">
              <div>
                <p className="text-[11px] text-orange-400 font-bold">Required Elements (DO NOT REMOVE):</p>
                <ul className="text-[11px] text-stone-500 mt-1 space-y-0.5 ml-2">
                  <li>• Instruction to generate "presentation slide outlines"</li>
                  <li>• Rule to start output with "SLIDE #" (no preamble text)</li>
                  <li>• Rule to use &#9656; markers (&#9656; TITLE:, &#9656; SUBTITLE:, etc.)</li>
                  <li>• Rule to NEVER use # markdown headers</li>
                  <li>• Rule to include ALL 7 sections for every slide</li>
                  <li>• Rule to avoid explanatory text like "Here is..." or "Based on..."</li>
                </ul>
              </div>
              <div>
                <p className="text-[11px] text-orange-400 font-bold">Safe to Modify:</p>
                <ul className="text-[11px] text-stone-500 mt-1 space-y-0.5 ml-2">
                  <li>• Tone instructions (e.g., "Be concise" vs "Be detailed")</li>
                  <li>• Creativity level (e.g., "Be creative with titles" or "Use straightforward language")</li>
                  <li>• Industry-specific terminology preferences</li>
                  <li>• Additional formatting rules that don't conflict with required elements</li>
                  <li>• Emphasis on certain aspects (e.g., "Focus on visual descriptions")</li>
                </ul>
              </div>
              <div>
                <p className="text-[11px] text-orange-400 font-bold">Example Customization:</p>
                <p className="text-[10px] text-stone-500 mt-1 bg-stone-950 p-2 rounded font-mono">
                  Add: "Use professional business language suitable for executive presentations. Avoid jargon and keep bullet points to 10 words or fewer."
                </p>
              </div>
            </div>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Generation Rules</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed mb-2">
              These are detailed instructions included in the user prompt that specify exactly how slides should be formatted, what sections to include, and what rules to follow for different layout types.
              This is where the actual output structure is defined.
            </p>
            <div className="mt-3 space-y-2">
              <div>
                <p className="text-[11px] text-orange-400 font-bold">Required Sections (Must Keep All 7):</p>
                <ul className="text-[11px] text-stone-500 mt-1 space-y-0.5 ml-2">
                  <li>• <span className="text-orange-400/70">&#9656; TITLE:</span> The main headline for the slide</li>
                  <li>• <span className="text-orange-400/70">&#9656; SUBTITLE:</span> Supporting text beneath the title</li>
                  <li>• <span className="text-orange-400/70">&#9656; LAYOUT STRUCTURE:</span> How content is arranged visually</li>
                  <li>• <span className="text-orange-400/70">&#9656; COPY/TEXT CONTENT:</span> The actual body text and bullet points</li>
                  <li>• <span className="text-orange-400/70">&#9656; VISUAL STYLING:</span> Mood, texture, atmosphere, and typography notes (no color references — colors handled by theme system)</li>
                  <li>• <span className="text-orange-400/70">&#9656; REQUIRED ASSETS:</span> Typed assets: [Image], [Video], [Icon/Logo], [Infograph], [Timeline], [Image Background]</li>
                  <li>• <span className="text-orange-400/70">&#9656; COMPONENT GEOMETRY:</span> JSON code block with x/y/width/height coordinates for Google Slides automation</li>
                </ul>
              </div>
              <div>
                <p className="text-[11px] text-orange-400 font-bold">Safe to Modify:</p>
                <ul className="text-[11px] text-stone-500 mt-1 space-y-0.5 ml-2">
                  <li>• Content length limits (e.g., "max 3 bullet points per section")</li>
                  <li>• Which layouts should have body text vs. title-only</li>
                  <li>• Asset requirements and suggestions</li>
                  <li>• Visual styling guidelines and color preferences</li>
                  <li>• Rules for specific layout types (e.g., "Caption slides should have 2 bullet points max")</li>
                  <li>• Industry-specific content formatting</li>
                </ul>
              </div>
              <div>
                <p className="text-[11px] text-orange-400 font-bold">Layout-Specific Rules:</p>
                <p className="text-[11px] text-stone-500 mt-1">
                  The default rules specify that certain layouts (Title slide, Section header, Title Page w/Gradient, Title only, Big number) should only have title and subtitle with no body text.
                  You can modify which layouts follow this rule by editing the list in rule #7.
                </p>
              </div>
              <div>
                <p className="text-[11px] text-orange-400 font-bold">Example Customization:</p>
                <p className="text-[10px] text-stone-500 mt-1 bg-stone-950 p-2 rounded font-mono">
                  Change: "max 4 sentences per section" &rarr; "max 2 sentences per section, use punchy language"
                  <br/>Add: "8. Always suggest a specific stock photo description in REQUIRED ASSETS"
                </p>
              </div>
            </div>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">How They Work Together</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed">
              When you generate a slide, the system combines these prompts with your uploaded documents and page request:
            </p>
            <ol className="text-[11px] text-stone-500 mt-2 space-y-1 ml-2">
              <li>1. <span className="text-stone-400">API System Message</span> is sent as the AI's system instruction</li>
              <li>2. Your <span className="text-stone-400">uploaded documents</span> are included as context</li>
              <li>3. Your <span className="text-stone-400">Deck Context & Guidelines</span> from the main interface is added</li>
              <li>4. The selected <span className="text-stone-400">layout type</span> and <span className="text-stone-400">page request</span> are specified</li>
              <li>5. <span className="text-stone-400">Generation Rules</span> with the output format template are appended</li>
              <li>6. The AI generates content following all these instructions</li>
            </ol>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Visual Assets System Prompt</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Theme Color Generation:</span> Haiku prompt for AI theme color palette generation</li>
              <li>• <span className="text-stone-300">Shared Rules (All Models):</span> Common formatting and data completeness rules for all image models</li>
              <li>• <span className="text-stone-300">Midjourney Prompt:</span> Model-specific rules for Midjourney v6 syntax</li>
              <li>• <span className="text-stone-300">Flux Prompt:</span> Model-specific rules for Flux image generation</li>
              <li>• <span className="text-stone-300">Nano Banana Prompt:</span> Model-specific rules for Nano Banana</li>
              <li>• <span className="text-stone-300">Chat GPT / DALL-E Prompt:</span> Model-specific rules for ChatGPT/DALL-E 3</li>
              <li>• <span className="text-stone-300">Image Prompt - API System Message:</span> Core instruction for the Claude API call that generates image prompts</li>
            </ul>
          </div>
        </div>
      </section>
      </div>
      )}

      {/* ═══ OUTPUT FORMAT ═══ */}
      {helpPage === 'output-format' && (
      <div className="space-y-5">
      <section>
        <h3 className="text-sm font-bold text-orange-400 uppercase tracking-wide mb-3">Understanding Output Format</h3>
        <p className="text-xs text-stone-300 leading-relaxed mb-3">
          Output formats define the markdown schema used when exporting slides. The system parses generated content based on these patterns.
          All format schemas are accessible in the Settings panel under the Format tab as collapsible sections.
        </p>
        <div className="space-y-3">
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-1">Single Page Export Schema</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed">
              Template for individual slide exports. Each slide uses this structure.
            </p>
            <p className="text-[11px] text-stone-500 mt-2"><span className="text-orange-400">Critical elements:</span> SLIDE #[NUMBER] — [Layout Name] header, ═══ delimiters, and all six &#9656; section markers must be present for the parser to work correctly.</p>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-1">Full Deck Export Schema</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed">
              Template showing how multiple slides are concatenated in a full deck export. Each slide follows the single page format, separated by delimiters.
            </p>
            <p className="text-[11px] text-stone-500 mt-2"><span className="text-orange-400">Critical elements:</span> Consistent delimiter pattern between slides (═══════), sequential slide numbering format.</p>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-1">Visual Deck Export Schema (VIS_DECKOUTLINE)</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed">
              Extended export format that wraps the standard DECKOUTLINE with a deck summary header (title, page count, selected theme colors, visual description)
              and an alternate themes footer listing all unused themes. This schema is read-only and cannot be edited.
            </p>
            <p className="text-[11px] text-stone-500 mt-2"><span className="text-orange-400">How to use:</span> In the Import/Export modal, check "Include theme colors & deck visual description" to switch the download button to VIS_DECKOUTLINE format. The file is named <span className="text-orange-400 font-mono">PROJECTNAME_VIS_DECKOUTLINE.md</span>.</p>
            <p className="text-[11px] text-stone-500 mt-1"><span className="text-orange-400">Importing:</span> VIS_DECKOUTLINE files can be imported back — the system will parse theme colors from the header and footer and restore them automatically.</p>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-1">Image Prompt Export Schema</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed">
              Template showing the markdown output format for generated image prompts. Each asset includes title, aspect ratio, and the full prompt text.
            </p>
            <p className="text-[11px] text-stone-500 mt-2"><span className="text-orange-400">How to use:</span> This schema defines how the DECKNAME_IMG_PROMPTS.md file is structured. Assets are grouped by slide number with formatted prompt blocks.</p>
          </div>
        </div>
      </section>
      </div>
      )}

      {/* ═══ THEME GENERATOR ═══ */}
      {helpPage === 'theme' && (
      <div className="space-y-5">
      <section>
        <h3 className="text-sm font-bold text-orange-400 uppercase tracking-wide mb-3">Theme Generator</h3>
        <p className="text-xs text-stone-300 leading-relaxed mb-3">
          The Theme Generator creates color palettes tailored to your deck content using the Haiku AI model. Theme colors are applied in the slide visualizer preview and can be exported with the VIS_DECKOUTLINE format.
        </p>
        <div className="space-y-3">
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">How It Works</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Enable:</span> Check "Theme Generator" next to Deck Context & Guidelines</li>
              <li>• <span className="text-stone-300">Auto-generation:</span> When enabled, themes are generated automatically after each deck or page generation</li>
              <li>• <span className="text-stone-300">Context-aware:</span> Haiku reads your deck context, slide titles, and file content to create relevant palettes</li>
              <li>• <span className="text-stone-300">3 themes per batch:</span> Each generation produces 3 new color themes</li>
              <li>• <span className="text-stone-300">Each theme = 4 colors:</span> Background, Accent, Secondary, Body Text</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Visualizer Controls</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Left/Right arrows:</span> Cycle through available themes (presets + generated)</li>
              <li>• <span className="text-stone-300">Refresh button:</span> Generate a new batch of 3 themes (icon spins orange while generating)</li>
              <li>• <span className="text-stone-300">Color swatches:</span> Show the 4 colors of the active theme with hex codes</li>
              <li>• <span className="text-stone-300">Theme name & index:</span> Displayed in orange next to the swatches</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Preset vs Generated</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed">
              4 preset themes are always available: Black & Orange, Orange & Black, Black & White, White & Black.
              When Theme Generator is disabled (checkbox unchecked), only these presets are used. When enabled,
              AI-generated themes are added after the presets and the first generated theme is auto-selected.
            </p>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Visual Styling — No Color Rule</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed">
              Slide outlines never include color references in the VISUAL STYLING section. This is by design — colors are handled
              separately by the theme system. Visual styling descriptions focus only on mood, texture, atmosphere, typography, and composition.
            </p>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Theme Prompt Customization</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed">
              The Haiku prompt used for theme generation can be customized in Settings &rarr; Prompts tab &rarr; "Theme Color Generation".
              This controls how the AI interprets your content and generates color palettes. Requires unlocking the prompts tab.
            </p>
          </div>
        </div>
      </section>
      </div>
      )}

      {/* ═══ IMAGE PROMPT GENERATION ═══ */}
      {helpPage === 'image-prompts' && (
      <div className="space-y-5">
      <section>
        <h3 className="text-sm font-bold text-orange-400 uppercase tracking-wide mb-3">Image Prompt Generation</h3>
        <p className="text-xs text-stone-300 leading-relaxed mb-4">
          The Image Prompt Generation system creates detailed AI image prompts for every visual asset defined in your slide outlines.
          Prompts are generated at export time and downloaded as a separate markdown file alongside your deck outline.
        </p>
        <div className="space-y-3">
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">How It Works</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li>• <span className="text-stone-300">Export-triggered:</span> Image prompts are ONLY generated when you click the export button with "Generate Image Prompts" enabled</li>
              <li>• <span className="text-stone-300">Asset extraction:</span> The system scans all slides and extracts visual assets from the &#9656; REQUIRED ASSETS section</li>
              <li>• <span className="text-stone-300">Logo/Icon skip:</span> Assets typed as Icon or Logo are automatically skipped since they represent existing brand assets</li>
              <li>• <span className="text-stone-300">Context-aware:</span> The AI uses your deck visual description, deck context, and slide content to create relevant prompts</li>
              <li>• <span className="text-stone-300">Model-specific:</span> Prompts are tailored to the syntax and best practices of your selected AI image model</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Using Image Prompts at Export</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li>• <span className="text-stone-300">Step 1:</span> Open the Import/Export modal from the header</li>
              <li>• <span className="text-stone-300">Step 2:</span> Check "Generate Image Prompts" checkbox</li>
              <li>• <span className="text-stone-300">Step 3:</span> Select your target model from the dropdown (Midjourney, Flux, Nano Banana, or Chat GPT)</li>
              <li>• <span className="text-stone-300">Step 4:</span> Click the export button — your outline downloads first, then image prompts are generated and downloaded as a separate file</li>
              <li>• <span className="text-stone-300">Output file:</span> Downloaded as DECKNAME_IMG_PROMPTS.md</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Supported AI Image Models</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li>• <span className="text-stone-300">Midjourney:</span> Comma-separated descriptors, camera references, quality tags, v6 syntax</li>
              <li>• <span className="text-stone-300">Flux:</span> Natural language descriptions, text-in-image support, material textures</li>
              <li>• <span className="text-stone-300">Nano Banana:</span> Composition-focused, visual hierarchy emphasis</li>
              <li>• <span className="text-stone-300">Chat GPT / DALL-E:</span> Paragraph-style prompts, spatial relationships, DALL-E 3 optimized</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Output Format</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed mb-2">
              The exported markdown file includes a header with the deck visual description, followed by assets grouped by slide:
            </p>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">&#9656; ASSET TITLE:</span> Name and type of the visual asset</li>
              <li>• <span className="text-stone-300">&#9656; ASPECT RATIO:</span> Recommended dimensions for the asset</li>
              <li>• <span className="text-stone-300">&#9656; PROMPT:</span> Full AI-optimized image generation prompt</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Customizing Image Prompts</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed">
              Image prompt system prompts can be customized in Settings &rarr; Prompts tab &rarr; "Visual Assets System Prompt" section.
              You can edit the shared rules (applied to all models), individual model-specific prompts, and the API system message.
              The output format template is editable in Settings &rarr; Format tab &rarr; "Image Prompt Export Schema".
            </p>
          </div>
        </div>
      </section>
      </div>
      )}

      {/* ═══ VISUAL ASSET PLACEMENT ═══ */}
      {helpPage === 'asset-placement' && (
      <div className="space-y-5">
      <section>
        <h3 className="text-sm font-bold text-orange-400 uppercase tracking-wide mb-3">Visual Asset Placement</h3>
        <p className="text-xs text-stone-300 leading-relaxed mb-4">
          Visual Asset Placement allows you to embed your own uploaded images and videos directly into generated slide outlines.
          When enabled, the AI reviews your visual assets and assigns them to contextually matching slide frames. The visualizer then renders your actual images instead of placeholder boxes.
        </p>
        <div className="space-y-3">
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">How to Enable</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li>• <span className="text-stone-300">Use Uploaded Assets:</span> Check this box in Section 1 (next to Theme Generator) to include images and videos you uploaded via the file upload area</li>
              <li>• <span className="text-stone-300">Use Project Assets:</span> Check this box to include visual assets stored in the currently selected project</li>
              <li>• <span className="text-stone-300">Both can be enabled simultaneously</span> — the system combines assets from both sources</li>
              <li>• <span className="text-stone-300">Non-destructive:</span> Unchecking both boxes returns the system to its default behavior with no side effects</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">How It Works</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li>• <span className="text-stone-300">AI-driven placement:</span> The AI sees your uploaded assets and decides which frames they best match based on slide content and visual context</li>
              <li>• <span className="text-stone-300">Marker system:</span> Placed assets appear in the REQUIRED ASSETS section with a {"<<filename>>"} marker (e.g., {"<<hero_shot.jpg>>"}) that links the frame to your uploaded file</li>
              <li>• <span className="text-stone-300">Native aspect ratios:</span> The visualizer automatically detects each image's native dimensions and renders it at its true aspect ratio, ignoring any AI-specified ratio</li>
              <li>• <span className="text-stone-300">Unplaced frames:</span> Any frames that don't have a matching uploaded asset are shown as the usual placeholder boxes with image prompt descriptions</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Supported File Types</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li>• <span className="text-stone-300">Images:</span> JPG, PNG, GIF, WebP, BMP, TIFF, SVG</li>
              <li>• <span className="text-stone-300">Videos:</span> MP4, MOV, WebM, AVI, MKV — displayed as auto-generated thumbnail frames with a play icon overlay</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Regeneration & Editing</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li>• <span className="text-stone-300">Preserved on regeneration:</span> When you regenerate a page, placed asset markers are preserved automatically. The AI is instructed to keep existing {"<<filename>>"} entries verbatim</li>
              <li>• <span className="text-stone-300">Request specific placements:</span> Use the revision prompt to direct the AI, e.g., "use hero_shot.jpg for the main image" or "remove the team photo from this slide"</li>
              <li>• <span className="text-stone-300">Full Deck mode:</span> Each asset is placed once across the entire deck — the AI distributes your uploads across slides where they contextually fit best</li>
              <li>• <span className="text-stone-300">Manual editing:</span> You can edit the raw markdown to add, remove, or change {"<<filename>>"} markers directly in text view</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Exporting with Placed Assets</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li>• <span className="text-stone-300">DECKOUTLINE.md / VIS_DECKOUTLINE.md:</span> The {"<<filename>>"} markers remain in the exported markdown for reference</li>
              <li>• <span className="text-stone-300">Export Placed Visual Assets:</span> Check this option in the export modal to download all placed image/video files as individually numbered files (e.g., PROJECTNAME_VIS_ASSETS_01_hero.jpg)</li>
              <li>• <span className="text-stone-300">Image Prompts:</span> When generating image prompts at export, frames with placed assets are automatically skipped — prompts are only generated for unplaced frames</li>
              <li>• <span className="text-stone-300">Export folder:</span> Use the Browse button in the export modal to select a custom output folder. The selected folder is remembered between sessions</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Tips</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• Name your files descriptively — "product_hero.jpg" gives the AI better context for placement than "IMG_4521.jpg"</li>
              <li>• Upload the right number of images for your deck — if you have 10 slides with 2 frames each, 5-8 unique images works well</li>
              <li>• Use high-resolution images — the visualizer renders at the slide preview size, but exports will reference your original files</li>
              <li>• Combine with Image Prompts — placed assets fill matched frames, and Image Prompts generates prompts for the remaining unplaced frames</li>
            </ul>
          </div>
        </div>
      </section>
      </div>
      )}

      {/* ═══ SLIDE LAYOUTS ═══ */}
      {helpPage === 'layouts' && (
      <div className="space-y-5">
      <section>
        <h3 className="text-sm font-bold text-orange-400 uppercase tracking-wide mb-3">Available Slide Layouts</h3>
        <p className="text-xs text-stone-300 leading-relaxed mb-3">
          15 layout types are available. Layouts with visual assets have maximum asset limits enforced by the system. Column layouts (2, 3, 4) feature dynamic image sizing that adjusts asset height based on text content volume.
        </p>
        <div className="space-y-3">
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Column Layouts — Visual Assets Above Text</h4>
            <p className="text-[11px] text-stone-400 leading-relaxed mb-2">
              These layouts display visual assets in a row above the text columns. Asset height dynamically adjusts based on text content length — more text causes images to shrink, less text allows images to stay larger.
            </p>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li>• <span className="text-stone-300 font-bold">Title and two columns</span> — Two side-by-side text columns with up to <span className="text-orange-400 font-bold">4 visual assets</span> above. Columns separated by --- in copy content. Assets centered above matching column widths (1-2 images) or packed left (3-4 images).</li>
              <li>• <span className="text-stone-300 font-bold">Title and three columns</span> — Three text columns with up to <span className="text-orange-400 font-bold">4 visual assets</span> above. Columns separated by --- dividers. Ideal for comparing three items, phases, or categories.</li>
              <li>• <span className="text-stone-300 font-bold">Title and four columns</span> — Four text columns with up to <span className="text-orange-400 font-bold">4 visual assets</span> above. Columns separated by --- dividers. Best for process flows, phase breakdowns, or multi-category comparisons.</li>
            </ul>
            <div className="mt-2 bg-stone-950 p-2 rounded">
              <p className="text-[10px] text-stone-500 leading-relaxed">
                <span className="text-orange-400 font-bold">Dynamic sizing:</span> Image row height ranges from 30-57% of the content area depending on asset count and text length. Short text = larger images. Long text = smaller images. Aspect ratios are always preserved.
              </p>
            </div>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Single Column & Split Layouts</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li>• <span className="text-stone-300 font-bold">One column text</span> — Text on the left with up to <span className="text-orange-400 font-bold">3 visual assets</span> stacked on the right side, plus <span className="text-orange-400 font-bold">1 timeline asset</span> if present (4 total). Assets span the full height of the content area.</li>
              <li>• <span className="text-stone-300 font-bold">Section title and description</span> — Up to <span className="text-orange-400 font-bold">3 visual assets</span> fill the left half with the title/subtitle overlaid. The right half displays body text (bullets, numbered lists, paragraphs — no section headers).</li>
              <li>• <span className="text-stone-300 font-bold">Title and body</span> — Standard content slide with title, subtitle, and body text. Supports visual assets as background or inline references.</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Title-Only Layouts (No Body Text)</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li>• <span className="text-stone-300 font-bold">Title slide</span> — Centered title and subtitle. Used for opening slides and section transitions.</li>
              <li>• <span className="text-stone-300 font-bold">Section header</span> — Large divider text for breaking a deck into sections.</li>
              <li>• <span className="text-stone-300 font-bold">Title only</span> — Minimal slide with title and subtitle. Useful for visual-heavy slides where the image background is the focus.</li>
              <li>• <span className="text-stone-300 font-bold">Big number</span> — Large statistic or metric as the focal point with a supporting subtitle.</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Specialty Layouts</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li>• <span className="text-stone-300 font-bold">Main point</span> — Emphasized key message with large centered text. Draws attention to a single important statement.</li>
              <li>• <span className="text-stone-300 font-bold">Caption</span> — Image-focused layout with minimal text overlay. Best for hero imagery, product shots, or cinematic moments.</li>
              <li>• <span className="text-stone-300 font-bold">Blank</span> — Empty layout for fully custom content arrangement.</li>
              <li>• <span className="text-stone-300 font-bold">Section Header w/Gradient</span> — Section header variant with a gradient background effect.</li>
              <li>• <span className="text-stone-300 font-bold">Title Page w/Gradient</span> — Title slide variant with a gradient background effect.</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Visual Asset Limits Summary</h4>
            <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-[11px] ml-2">
              <div className="text-stone-400">Title and two columns</div>
              <div className="text-orange-400 font-bold">4 assets max</div>
              <div className="text-stone-400">Title and three columns</div>
              <div className="text-orange-400 font-bold">4 assets max</div>
              <div className="text-stone-400">Title and four columns</div>
              <div className="text-orange-400 font-bold">4 assets max</div>
              <div className="text-stone-400">One column text</div>
              <div className="text-orange-400 font-bold">3 side + 1 timeline</div>
              <div className="text-stone-400">Section title and description</div>
              <div className="text-orange-400 font-bold">3 assets max</div>
            </div>
            <p className="text-[10px] text-stone-500 mt-2 ml-2">
              Assets beyond these limits are not rendered in the visualizer. The AI is instructed to respect these limits when generating content.
            </p>
          </div>
        </div>
      </section>
      </div>
      )}

      {/* ═══ SETTINGS PANEL ═══ */}
      {helpPage === 'settings' && (
      <div className="space-y-5">
      <section>
        <h3 className="text-sm font-bold text-orange-400 uppercase tracking-wide mb-3">Settings Panel</h3>
        <p className="text-xs text-stone-300 leading-relaxed mb-3">
          The Settings panel (gear icon) contains all system prompts and output format schemas in collapsible dropdown sections.
          Each section has a title bar that expands/collapses the content and a "Reset to default" button.
        </p>
        <div className="space-y-3">
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Prompts Tab</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Single Page - API System Message:</span> Core system instruction for single page generation</li>
              <li>• <span className="text-stone-300">Single Page - Generation Rules:</span> Formatting rules and constraints for single page output</li>
              <li>• <span className="text-stone-300">Full Deck - API System Message:</span> Core system instruction for full deck generation</li>
              <li>• <span className="text-stone-300">Full Deck - Generation Rules:</span> Formatting rules and constraints for full deck output</li>
              <li>• <span className="text-stone-300">Theme Color Generation:</span> System prompt for AI theme color generation</li>
              <li>• <span className="text-stone-300">AI Rewrite Prompts:</span> Customize the 5 rewrite modes (Relaxed, Formal, Extend, Shorten, Custom Editor)</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Visual Assets System Prompt</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Shared Rules (All Models):</span> Common formatting rules for all image models</li>
              <li>• <span className="text-stone-300">Midjourney / Flux / Nano Banana / Chat GPT:</span> Model-specific prompt rules</li>
              <li>• <span className="text-stone-300">Image Prompt - API System Message:</span> Core instruction for the image prompt generation API call</li>
            </ul>
          </div>
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Format Tab</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Single Page Export Schema:</span> Markdown structure for individual slide exports</li>
              <li>• <span className="text-stone-300">Full Deck Export Schema:</span> Markdown structure for complete deck exports</li>
              <li>• <span className="text-stone-300">Visual Deck Export Schema:</span> Read-only schema showing the VIS_DECKOUTLINE format structure</li>
              <li>• <span className="text-stone-300">Image Prompt Export Schema:</span> Markdown structure for AI image prompt exports</li>
            </ul>
          </div>
        </div>
      </section>
      </div>
      )}

      {/* ═══ TIPS ═══ */}
      {helpPage === 'tips' && (
      <div className="space-y-5">
      <section>
        <h3 className="text-sm font-bold text-orange-400 uppercase tracking-wide mb-3">Tips for Best Results</h3>
        <ul className="text-xs text-stone-300 leading-relaxed space-y-1">
          <li>• <span className="text-orange-400">Be specific</span> in your deck context about tone, audience, and visual style preferences.</li>
          <li>• <span className="text-orange-400">Use descriptive page requests</span> that reference specific content from your uploaded documents.</li>
          <li>• <span className="text-orange-400">Review and edit</span> generated content in the text view before exporting.</li>
          <li>• <span className="text-orange-400">Use the visualizer</span> to preview how your slide will look with different layouts and theme colors.</li>
          <li>• <span className="text-orange-400">Enable Theme Generator</span> for AI-powered color palettes that match your content.</li>
          <li>• <span className="text-orange-400">Cycle themes</span> with arrow buttons to compare palettes before exporting.</li>
          <li>• <span className="text-orange-400">Export with VIS format</span> to include theme colors and visual descriptions for downstream design tools.</li>
          <li>• <span className="text-orange-400">For full decks</span>, include desired page count in your deck context (e.g., "Create a 10-slide presentation...").</li>
          <li>• <span className="text-orange-400">Lock settings</span> after configuring to prevent accidental changes during your session.</li>
          <li>• <span className="text-orange-400">Collapse settings sections</span> you don't need to keep the panel tidy.</li>
          <li>• <span className="text-orange-400">Use AI Rewrite</span> to quickly adjust tone — select text, right-click, and choose a rewrite mode.</li>
          <li>• <span className="text-orange-400">Generate image prompts</span> at export time to get model-specific prompts for all visual assets in your deck.</li>
          <li>• <span className="text-orange-400">Column layouts support up to 4 images</span> — Two, three, and four column layouts can display up to 4 visual assets above the text columns. Images are dynamically sized based on text length.</li>
          <li>• <span className="text-orange-400">Use --- separators</span> in column layouts — The AI separates column content with --- dividers. Each section becomes one column.</li>
          <li>• <span className="text-orange-400">Match image count to columns</span> — For the best visual balance in column layouts, request one image per column (e.g., 3 images for three columns).</li>
          <li>• <span className="text-orange-400">Control image sizes with text length</span> — In column layouts, adding more bullet points causes images to shrink dynamically. Use shorter text for larger images.</li>
          <li>• <span className="text-orange-400">Place your own images</span> — Enable "Use Uploaded Assets" or "Use Project Assets" to have the AI embed your images directly into slide frames.</li>
          <li>• <span className="text-orange-400">Name image files descriptively</span> — "product_hero.jpg" gives the AI much better context for placement than "IMG_4521.jpg".</li>
          <li>• <span className="text-orange-400">Set an export folder</span> — Use the Browse button in the export modal to save files directly to a specific folder instead of the browser's downloads.</li>
          <li>• <span className="text-orange-400">Include contact info</span> in your Deck Context prompt — emails and contact details from both source documents and the deck context are included in OUTRO slides.</li>
          <li>• <span className="text-orange-400">Use the formatting toolbar</span> for quick markdown formatting — bold, italic, bullets, and numbered lists.</li>
        </ul>
      </section>

      <section className="bg-orange-500/10 border border-orange-500/30 rounded-sm p-3">
        <h3 className="text-xs font-bold text-orange-400 uppercase tracking-wide mb-2">Important Notes</h3>
        <ul className="text-xs text-stone-300 leading-relaxed space-y-1">
          <li>• Modifying system prompts incorrectly may cause parsing errors or unexpected output formats.</li>
          <li>• Always use "Reset to default" if you encounter issues after editing prompts.</li>
          <li>• The &#9656; markers and ═══ delimiters are required for the system to parse slides correctly.</li>
          <li>• Changes to prompts and formats are applied immediately but are not persisted between sessions.</li>
          <li>• Theme generation requires an active API connection. The refresh button spins orange while generating.</li>
          <li>• Visual Deck Export Schema is read-only and cannot be edited — it reflects the fixed VIS_DECKOUTLINE format.</li>
          <li>• VISUAL STYLING sections in slide outlines intentionally exclude color references — colors are handled by the theme system.</li>
          <li>• Column layouts (2, 3, 4) enforce a maximum of 4 visual assets. One column text supports 3 side assets + 1 timeline. Section title and description supports up to 3 assets. Extra assets beyond these limits are not displayed.</li>
        </ul>
      </section>
      </div>
      )}

      {/* ═══ DOWNLOAD SLIDES EXTENSION ═══ */}
      {helpPage === 'slides-extension' && (
      <div className="space-y-5">
      <section>
        <h3 className="text-sm font-bold text-orange-400 uppercase tracking-wide mb-3">Download Slides Extension</h3>
        <p className="text-xs text-stone-300 leading-relaxed mb-4">
          The D.O.G. Bridge is a Google Slides Apps Script extension that reads your exported VIS_DECKOUTLINE markdown files and programmatically builds
          Google Slides decks with precise coordinate-based placement. It bridges the gap between D.O.G.'s outline generation and your final presentation.
        </p>

        <div className="space-y-3">
          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">What It Does</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li>• <span className="text-stone-300">Parses DECKOUTLINE and VIS_DECKOUTLINE</span> markdown files into structured slide data</li>
              <li>• <span className="text-stone-300">Creates slides</span> with matched layout templates from your Google Slides theme</li>
              <li>• <span className="text-stone-300">Positions text boxes</span> using COMPONENT GEOMETRY coordinates for pixel-perfect placement</li>
              <li>• <span className="text-stone-300">Injects formatted text</span> with bold, bullets, numbered lists, and section headers</li>
              <li>• <span className="text-stone-300">Applies theme colors</span> from your VIS_DECKOUTLINE to backgrounds, titles, subtitles, and body text</li>
              <li>• <span className="text-stone-300">Creates asset placeholder frames</span> for images, videos, infographics, and timelines</li>
              <li>• <span className="text-stone-300">Places images from Google Drive</span> folders with fuzzy name matching</li>
            </ul>
          </div>

          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Installation Steps</h4>
            <ol className="text-[11px] text-stone-400 leading-relaxed space-y-1.5 ml-2">
              <li><span className="text-orange-400 font-bold">1.</span> Download both files below (<span className="text-stone-300">Code.gs</span> and <span className="text-stone-300">Sidebar.html</span>)</li>
              <li><span className="text-orange-400 font-bold">2.</span> Open a Google Slides presentation</li>
              <li><span className="text-orange-400 font-bold">3.</span> Go to <span className="text-stone-300">Extensions &rarr; Apps Script</span></li>
              <li><span className="text-orange-400 font-bold">4.</span> Replace the default Code.gs content with the downloaded <span className="text-stone-300">Code.gs</span> file</li>
              <li><span className="text-orange-400 font-bold">5.</span> Click the <span className="text-stone-300">+</span> next to Files, select <span className="text-stone-300">HTML</span>, name it <span className="text-stone-300">Sidebar</span>, and paste the <span className="text-stone-300">Sidebar.html</span> content</li>
              <li><span className="text-orange-400 font-bold">6.</span> Save and close the Apps Script editor</li>
              <li><span className="text-orange-400 font-bold">7.</span> Refresh your Google Slides — a new <span className="text-stone-300">"D.O.G. Bridge"</span> menu item will appear</li>
            </ol>
          </div>

          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Download Files</h4>
            <div className="space-y-2">
              <a
                href="./extensions/Code.gs"
                download="Code.gs"
                className="flex items-center gap-3 px-3 py-2.5 rounded-sm transition-colors hover:bg-stone-800"
                style={{ borderLeft: '3px solid #ea580c', backgroundColor: '#0c0a09' }}
              >
                <span className="text-orange-400 text-xs">&#8595;</span>
                <div>
                  <span className="text-[11px] text-orange-400 font-bold">Code.gs</span>
                  <span className="text-[10px] text-stone-500 ml-2">Server-side Apps Script</span>
                </div>
              </a>
              <a
                href="./extensions/Sidebar.html"
                download="Sidebar.html"
                className="flex items-center gap-3 px-3 py-2.5 rounded-sm transition-colors hover:bg-stone-800"
                style={{ borderLeft: '3px solid #ea580c', backgroundColor: '#0c0a09' }}
              >
                <span className="text-orange-400 text-xs">&#8595;</span>
                <div>
                  <span className="text-[11px] text-orange-400 font-bold">Sidebar.html</span>
                  <span className="text-[10px] text-stone-500 ml-2">Sidebar UI interface</span>
                </div>
              </a>
            </div>
          </div>

          <div className="bg-stone-900 p-3 rounded-sm border border-stone-700">
            <h4 className="text-xs font-bold text-orange-400 mb-2">Features</h4>
            <ul className="text-[11px] text-stone-400 leading-relaxed space-y-1 ml-2">
              <li>• <span className="text-stone-300">Full Deck or Single Page mode</span> — Build the entire deck or replace a single slide</li>
              <li>• <span className="text-stone-300">Theme color application</span> — Applies background, accent, secondary, and body text colors from your outline</li>
              <li>• <span className="text-stone-300">Coordinate-based text positioning</span> — Uses COMPONENT GEOMETRY JSON for precise element placement</li>
              <li>• <span className="text-stone-300">Asset placeholder creation</span> — Gray, outlined, or transparent placeholder frames for visual assets</li>
              <li>• <span className="text-stone-300">Auto-shrink text to fit</span> — Automatically reduces font size when text overflows its box</li>
              <li>• <span className="text-stone-300">Header/footer with date format detection</span> — Sets project name, date, and slide numbers from your theme's format</li>
              <li>• <span className="text-stone-300">Drive folder asset matching</span> — Fuzzy-matches uploaded images to placeholder frames by description</li>
              <li>• <span className="text-stone-300">Configurable settings</span> — Font sizes, placeholder styles, date formats, and debug mode</li>
            </ul>
          </div>
        </div>
      </section>
      </div>
      )}
      </div>
    </>
  );
}
